---
dependencies: null
description: A base class for all AI providers.
dev_dependencies:
  auto_exporter: ^4.0.0
  build_runner: ^2.6.0
  test: ^1.24.0
  very_good_analysis: any
environment:
  sdk: ^3.0.0
name: ai_box
homepage: https://github.com/normidar/ai_box
topics:
  - ai
  - chatgpt
  - grok
  - gemini
  - claude
version: 0.0.1
