include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]
  errors:
    sort_constructors_first: ignore
    public_member_api_docs: ignore
    one_member_abstracts: ignore
    invalid_annotation_target: ignore
    avoid_positional_boolean_parameters: ignore
    use_setters_to_change_properties: ignore
    prefer_asserts_with_message: ignore
