---
dependencies:
  ai_box: ^0.0.1
  api_http: ^0.0.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  mime: ^1.0.4
description: '''A gemini AI provider based on ai_box.'''
dev_dependencies:
  auto_exporter: any
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  test: ^1.24.0
  very_good_analysis: any
environment:
  sdk: ^3.4.0
homepage: https://github.com/normidar/ai_box
name: gemini_box
topics:
  - ai
  - gemini
  - ai-box
  - llm
  - google
version: 0.0.1